name: Build and Maybe Deploy
on:
  push:
    branches:
      - '*'
jobs:
  install-npm-all:
    timeout-minutes: 100
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: |
          df -h
          du -sh ~/.npm
          npm i no-one-left-behind
          df -h
          du -sh ~/.npm
